### ISSUE TITLE
error passing plugin with task, it fails if I have only 1 plugin with task

### ISSUE THREAD

**Issue by omazapa** [colav-playground/Kahi#6]
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 133, in run
    plugin_config[module_name] = self.workflow[module_name]
                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ranking_udea_works'

**Comment by omazapa** [comment]
fixed via 98b365df2c08518e192abff25f9bf6016376620d
